defaults:
  - model: thermo_kaem
  - training: cifar10
  - _self_

model:
  z_dim: 81
  seed: 0

  ebm:
    layer_widths: [200, 200]
    leakyrelu_leak: 0.2
    p0_stddev: 1.0
    mcmc:
      stepsize: 0.16
      numsteps: 60

  gen:
    mixed_precision: false
    gaussian_stddev: 0.3
    img_channels: 3
    groupnorm: false
    mcmc:
      stepsize: 0.01
      numsteps: 20

  kaem:
    mixture: true
    numquad: 25
    p0_stddev: 1.0
    domain_update_freq: 100
    domain_update_coverage: 0.99
    mixture_regularization: 0.0001

optim:
  gen:
    lr_init: 1e-4
    lr_end: 1e-5
    weight_decay: 1e-4
    beta1: 0.9
    beta2: 0.999
    warmup_fraction: 0.05

  ebm:
    lr_init: 5e-5
    lr_end: 5e-6
    weight_decay: 1e-4
    beta1: 0.9
    beta2: 0.999
    warmup_fraction: 0.05

  kaem:
    lr_init: 5e-5
    lr_end: 5e-6
    weight_decay: 1e-4
    beta1: 0.9
    beta2: 0.999
    warmup_fraction: 0.05


run_name: ${model.base}_${training.dataset}

logging:
  logdir: runs/${run_name}
  ckpt_dir: runs/${run_name}
  ckpt_every: 20
  sample_every: 10
  num_samples: 10

unbiased_metrics:
  batch_size_to_generate: 50
  num_samples: 20000
  regression_steps: [2000, 4000, 6000, 8000, 10000, 12000, 14000, 16000, 18000, 20000]
