model:
  z_dim: 81
  seed: 0
  base: kaem

  ebm:
    layer_widths: [100, 100]
    leakyrelu_leak: 0.1
    p0_stddev: 1.0
    mcmc:
      stepsize: 0.01
      numsteps: 5


  gen:
    mixed_precision: true
    gaussian_stddev: 0.3
    groupnorm: False
    leakyrelu_leak: 0.1
    blocks:
      - channels: 16
        kernel_size: 4
        stride: 1
        padding: VALID
      - channels: 8
        kernel_size: 4
        stride: 2
        padding: SAME
      - channels: 4
        kernel_size: 4
        stride: 2
        padding: SAME
    img_channels: 3
    mcmc:
      stepsize: 0.01
      numsteps: 10


  kaem:
    mixture: false
    numquad: 25
    p0_stddev: 1.0
    domain_update_freq: 100
    domain_update_coverage: 0.8
    mixture_regularization: 0.0001

  thermo:
    num_temps: 3
    annealing_cycle: 0
    powerlaw_start: 6
    powerlaw_end: 6

optim:
  gen:
    lr_init: 1e-4
    lr_end: 1e-5
    weight_decay: 1e-4
    beta1: 0.999
    beta2: 0.9
  ebm:
    lr_init: 2e-5
    lr_end: 2e-6
    weight_decay: 1e-5
    beta1: 0.999
    beta2: 0.9
  kaem:
    lr_init: 2e-5
    lr_end: 2e-6
    weight_decay: 1e-5
    beta1: 0.999
    beta2: 0.9

training:
  epochs: 4
  global_batch_size: 32
  dataset: fake32
  image_res: 32
  importance_finetune:
    type: residual
    start_fraction: 0.5


logging:
  logdir: /tmp
  ckpt_dir: /tmp
  ckpt_every: 1
  sample_every: 1
  num_samples: 10

unbiased_metrics:
  batch_size_to_generate: 50
  num_samples: 50
  regression_steps: [1000, 1200, 1300]


